spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/financial?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    solr:
      host: http://127.0.0.1:8983/solr
  servlet:
    multipart:
      file-size-threshold: 5MB
      max-request-size: 5MB
      max-file-size: 5MB



  mvc:
    static-path-pattern=/static/**:

mybatis:
  mapper-locations: classpath:mappers/*.xml
















debug: true
